Install composer for oficial image
joseluisq/alpine-php-fpm pull request #3
Opened 2021-12-27 16:17 UTC by tiagodevweb

Congratulations on the repository, I noticed some other improvements besides this PR one but I'm waiting for your approval to send others. I'm also looking for production versions, how about scaling up this repository for that?

2021-12-27 21:44 UTC, joseluisq requested changes
The PR itself is not bad but the problem is that it does other things not related to the PR itself like changing config file paths.

2021-12-27 23:26 UTC, tiagodevweb commented
alright, readjusted

2021-12-28 09:00 UTC, joseluisq requested changes

2021-12-28 10:43 UTC, tiagodevweb commented on 7.4-fpm/Dockerfile
> +COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
I understand, it looks better! Adjusted.

2021-12-28 11:20 UTC, joseluisq approved these changes

2021-12-28 11:22 UTC, merged

2021-12-28 11:23 UTC, joseluisq commented
Thanks 👍